#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="6489-Mueed")]
public partial class LINQLocalDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertPCMH_SURVEY_QUESTION(PCMH_SURVEY_QUESTION instance);
  partial void UpdatePCMH_SURVEY_QUESTION(PCMH_SURVEY_QUESTION instance);
  partial void DeletePCMH_SURVEY_QUESTION(PCMH_SURVEY_QUESTION instance);
  partial void InsertPCMH_SURVEY(PCMH_SURVEY instance);
  partial void UpdatePCMH_SURVEY(PCMH_SURVEY instance);
  partial void DeletePCMH_SURVEY(PCMH_SURVEY instance);
  #endregion
	
	public LINQLocalDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["_6489_MueedConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public LINQLocalDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public LINQLocalDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public LINQLocalDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public LINQLocalDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<DASHBOARD_DEFAULT_SETTING> DASHBOARD_DEFAULT_SETTINGs
	{
		get
		{
			return this.GetTable<DASHBOARD_DEFAULT_SETTING>();
		}
	}
	
	public System.Data.Linq.Table<PCMH_SURVEY_QUESTION> PCMH_SURVEY_QUESTIONs
	{
		get
		{
			return this.GetTable<PCMH_SURVEY_QUESTION>();
		}
	}
	
	public System.Data.Linq.Table<PCMH_SURVEY> PCMH_SURVEYs
	{
		get
		{
			return this.GetTable<PCMH_SURVEY>();
		}
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.PROC_GET_DASHBOARD_DEFAULT_SETTINGS")]
	public ISingleResult<PROC_GET_DASHBOARD_DEFAULT_SETTINGSResult> PROC_GET_DASHBOARD_DEFAULT_SETTINGS()
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		return ((ISingleResult<PROC_GET_DASHBOARD_DEFAULT_SETTINGSResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.PROC_UPDATE_DASHBOARD_DEFAULT_SETTINGS")]
	public int PROC_UPDATE_DASHBOARD_DEFAULT_SETTINGS([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SHOW_ITEM", DbType="Bit")] System.Nullable<bool> sHOW_ITEM, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DASH_ID", DbType="BigInt")] System.Nullable<long> dASH_ID)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sHOW_ITEM, dASH_ID);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.PCMH_PROC_GET_SURVEY_QUESTIONS")]
	public ISingleResult<PCMH_PROC_GET_SURVEY_QUESTIONSResult> PCMH_PROC_GET_SURVEY_QUESTIONS([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SURVEY_ID", DbType="BigInt")] System.Nullable<long> sURVEY_ID)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sURVEY_ID);
		return ((ISingleResult<PCMH_PROC_GET_SURVEY_QUESTIONSResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.PCMH_PROC_SEARCH_PATIENT")]
	public ISingleResult<PCMH_PROC_SEARCH_PATIENTResult> PCMH_PROC_SEARCH_PATIENT([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Search_Criteria", DbType="VarChar(2)")] string search_Criteria, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Search_Data", DbType="VarChar(50)")] string search_Data)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), search_Criteria, search_Data);
		return ((ISingleResult<PCMH_PROC_SEARCH_PATIENTResult>)(result.ReturnValue));
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DASHBOARD_DEFAULT_SETTINGS")]
public partial class DASHBOARD_DEFAULT_SETTING
{
	
	private System.Nullable<long> _DASHBOARD_SETTINGS_ID;
	
	private string _DASHBOARD_ITEM;
	
	private System.Nullable<bool> _SHOW_ITEM;
	
	private System.Nullable<int> _POSITION;
	
	public DASHBOARD_DEFAULT_SETTING()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DASHBOARD_SETTINGS_ID", DbType="BigInt")]
	public System.Nullable<long> DASHBOARD_SETTINGS_ID
	{
		get
		{
			return this._DASHBOARD_SETTINGS_ID;
		}
		set
		{
			if ((this._DASHBOARD_SETTINGS_ID != value))
			{
				this._DASHBOARD_SETTINGS_ID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DASHBOARD_ITEM", DbType="VarChar(100)")]
	public string DASHBOARD_ITEM
	{
		get
		{
			return this._DASHBOARD_ITEM;
		}
		set
		{
			if ((this._DASHBOARD_ITEM != value))
			{
				this._DASHBOARD_ITEM = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SHOW_ITEM", DbType="Bit")]
	public System.Nullable<bool> SHOW_ITEM
	{
		get
		{
			return this._SHOW_ITEM;
		}
		set
		{
			if ((this._SHOW_ITEM != value))
			{
				this._SHOW_ITEM = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POSITION", DbType="Int")]
	public System.Nullable<int> POSITION
	{
		get
		{
			return this._POSITION;
		}
		set
		{
			if ((this._POSITION != value))
			{
				this._POSITION = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PCMH_SURVEY_QUESTIONS")]
public partial class PCMH_SURVEY_QUESTION : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private long _PCMH_QUESTIONS_ID;
	
	private string _PCMH_QUESTION;
	
	private System.Nullable<long> _PRACTICE_CODE;
	
	private System.Nullable<bool> _DELETED;
	
	private string _CREATED_BY;
	
	private System.Nullable<System.DateTime> _CREATED_DATE;
	
	private string _MODIFIED_BY;
	
	private System.Nullable<System.DateTime> _MODIFIED_DATE;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPCMH_QUESTIONS_IDChanging(long value);
    partial void OnPCMH_QUESTIONS_IDChanged();
    partial void OnPCMH_QUESTIONChanging(string value);
    partial void OnPCMH_QUESTIONChanged();
    partial void OnPRACTICE_CODEChanging(System.Nullable<long> value);
    partial void OnPRACTICE_CODEChanged();
    partial void OnDELETEDChanging(System.Nullable<bool> value);
    partial void OnDELETEDChanged();
    partial void OnCREATED_BYChanging(string value);
    partial void OnCREATED_BYChanged();
    partial void OnCREATED_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnCREATED_DATEChanged();
    partial void OnMODIFIED_BYChanging(string value);
    partial void OnMODIFIED_BYChanged();
    partial void OnMODIFIED_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnMODIFIED_DATEChanged();
    #endregion
	
	public PCMH_SURVEY_QUESTION()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PCMH_QUESTIONS_ID", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
	public long PCMH_QUESTIONS_ID
	{
		get
		{
			return this._PCMH_QUESTIONS_ID;
		}
		set
		{
			if ((this._PCMH_QUESTIONS_ID != value))
			{
				this.OnPCMH_QUESTIONS_IDChanging(value);
				this.SendPropertyChanging();
				this._PCMH_QUESTIONS_ID = value;
				this.SendPropertyChanged("PCMH_QUESTIONS_ID");
				this.OnPCMH_QUESTIONS_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PCMH_QUESTION", DbType="VarChar(300)")]
	public string PCMH_QUESTION
	{
		get
		{
			return this._PCMH_QUESTION;
		}
		set
		{
			if ((this._PCMH_QUESTION != value))
			{
				this.OnPCMH_QUESTIONChanging(value);
				this.SendPropertyChanging();
				this._PCMH_QUESTION = value;
				this.SendPropertyChanged("PCMH_QUESTION");
				this.OnPCMH_QUESTIONChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRACTICE_CODE", DbType="BigInt")]
	public System.Nullable<long> PRACTICE_CODE
	{
		get
		{
			return this._PRACTICE_CODE;
		}
		set
		{
			if ((this._PRACTICE_CODE != value))
			{
				this.OnPRACTICE_CODEChanging(value);
				this.SendPropertyChanging();
				this._PRACTICE_CODE = value;
				this.SendPropertyChanged("PRACTICE_CODE");
				this.OnPRACTICE_CODEChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DELETED", DbType="Bit")]
	public System.Nullable<bool> DELETED
	{
		get
		{
			return this._DELETED;
		}
		set
		{
			if ((this._DELETED != value))
			{
				this.OnDELETEDChanging(value);
				this.SendPropertyChanging();
				this._DELETED = value;
				this.SendPropertyChanged("DELETED");
				this.OnDELETEDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATED_BY", DbType="VarChar(50)")]
	public string CREATED_BY
	{
		get
		{
			return this._CREATED_BY;
		}
		set
		{
			if ((this._CREATED_BY != value))
			{
				this.OnCREATED_BYChanging(value);
				this.SendPropertyChanging();
				this._CREATED_BY = value;
				this.SendPropertyChanged("CREATED_BY");
				this.OnCREATED_BYChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATED_DATE", DbType="DateTime")]
	public System.Nullable<System.DateTime> CREATED_DATE
	{
		get
		{
			return this._CREATED_DATE;
		}
		set
		{
			if ((this._CREATED_DATE != value))
			{
				this.OnCREATED_DATEChanging(value);
				this.SendPropertyChanging();
				this._CREATED_DATE = value;
				this.SendPropertyChanged("CREATED_DATE");
				this.OnCREATED_DATEChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODIFIED_BY", DbType="VarChar(50)")]
	public string MODIFIED_BY
	{
		get
		{
			return this._MODIFIED_BY;
		}
		set
		{
			if ((this._MODIFIED_BY != value))
			{
				this.OnMODIFIED_BYChanging(value);
				this.SendPropertyChanging();
				this._MODIFIED_BY = value;
				this.SendPropertyChanged("MODIFIED_BY");
				this.OnMODIFIED_BYChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODIFIED_DATE", DbType="DateTime")]
	public System.Nullable<System.DateTime> MODIFIED_DATE
	{
		get
		{
			return this._MODIFIED_DATE;
		}
		set
		{
			if ((this._MODIFIED_DATE != value))
			{
				this.OnMODIFIED_DATEChanging(value);
				this.SendPropertyChanging();
				this._MODIFIED_DATE = value;
				this.SendPropertyChanged("MODIFIED_DATE");
				this.OnMODIFIED_DATEChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PCMH_SURVEYS")]
public partial class PCMH_SURVEY : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private long _PCMH_SURVEY_ID;
	
	private string _PCMH_SURVEY_TITLE;
	
	private string _PCMH_SURVEY_DESCRIPTION;
	
	private System.Nullable<long> _PRACTICE_CODE;
	
	private System.Nullable<bool> _DELETED;
	
	private string _CREATED_BY;
	
	private System.Nullable<System.DateTime> _CREATED_DATE;
	
	private string _MODIFIED_BY;
	
	private System.Nullable<System.DateTime> _MODIFIED_DATE;
	
	private System.Nullable<int> _PCMH_Target;
	
	private System.Nullable<System.DateTime> _DeadLine_Date;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPCMH_SURVEY_IDChanging(long value);
    partial void OnPCMH_SURVEY_IDChanged();
    partial void OnPCMH_SURVEY_TITLEChanging(string value);
    partial void OnPCMH_SURVEY_TITLEChanged();
    partial void OnPCMH_SURVEY_DESCRIPTIONChanging(string value);
    partial void OnPCMH_SURVEY_DESCRIPTIONChanged();
    partial void OnPRACTICE_CODEChanging(System.Nullable<long> value);
    partial void OnPRACTICE_CODEChanged();
    partial void OnDELETEDChanging(System.Nullable<bool> value);
    partial void OnDELETEDChanged();
    partial void OnCREATED_BYChanging(string value);
    partial void OnCREATED_BYChanged();
    partial void OnCREATED_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnCREATED_DATEChanged();
    partial void OnMODIFIED_BYChanging(string value);
    partial void OnMODIFIED_BYChanged();
    partial void OnMODIFIED_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnMODIFIED_DATEChanged();
    partial void OnPCMH_TargetChanging(System.Nullable<int> value);
    partial void OnPCMH_TargetChanged();
    partial void OnDeadLine_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnDeadLine_DateChanged();
    #endregion
	
	public PCMH_SURVEY()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PCMH_SURVEY_ID", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
	public long PCMH_SURVEY_ID
	{
		get
		{
			return this._PCMH_SURVEY_ID;
		}
		set
		{
			if ((this._PCMH_SURVEY_ID != value))
			{
				this.OnPCMH_SURVEY_IDChanging(value);
				this.SendPropertyChanging();
				this._PCMH_SURVEY_ID = value;
				this.SendPropertyChanged("PCMH_SURVEY_ID");
				this.OnPCMH_SURVEY_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PCMH_SURVEY_TITLE", DbType="VarChar(50)")]
	public string PCMH_SURVEY_TITLE
	{
		get
		{
			return this._PCMH_SURVEY_TITLE;
		}
		set
		{
			if ((this._PCMH_SURVEY_TITLE != value))
			{
				this.OnPCMH_SURVEY_TITLEChanging(value);
				this.SendPropertyChanging();
				this._PCMH_SURVEY_TITLE = value;
				this.SendPropertyChanged("PCMH_SURVEY_TITLE");
				this.OnPCMH_SURVEY_TITLEChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PCMH_SURVEY_DESCRIPTION", DbType="VarChar(300)")]
	public string PCMH_SURVEY_DESCRIPTION
	{
		get
		{
			return this._PCMH_SURVEY_DESCRIPTION;
		}
		set
		{
			if ((this._PCMH_SURVEY_DESCRIPTION != value))
			{
				this.OnPCMH_SURVEY_DESCRIPTIONChanging(value);
				this.SendPropertyChanging();
				this._PCMH_SURVEY_DESCRIPTION = value;
				this.SendPropertyChanged("PCMH_SURVEY_DESCRIPTION");
				this.OnPCMH_SURVEY_DESCRIPTIONChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRACTICE_CODE", DbType="BigInt")]
	public System.Nullable<long> PRACTICE_CODE
	{
		get
		{
			return this._PRACTICE_CODE;
		}
		set
		{
			if ((this._PRACTICE_CODE != value))
			{
				this.OnPRACTICE_CODEChanging(value);
				this.SendPropertyChanging();
				this._PRACTICE_CODE = value;
				this.SendPropertyChanged("PRACTICE_CODE");
				this.OnPRACTICE_CODEChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DELETED", DbType="Bit")]
	public System.Nullable<bool> DELETED
	{
		get
		{
			return this._DELETED;
		}
		set
		{
			if ((this._DELETED != value))
			{
				this.OnDELETEDChanging(value);
				this.SendPropertyChanging();
				this._DELETED = value;
				this.SendPropertyChanged("DELETED");
				this.OnDELETEDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATED_BY", DbType="VarChar(50)")]
	public string CREATED_BY
	{
		get
		{
			return this._CREATED_BY;
		}
		set
		{
			if ((this._CREATED_BY != value))
			{
				this.OnCREATED_BYChanging(value);
				this.SendPropertyChanging();
				this._CREATED_BY = value;
				this.SendPropertyChanged("CREATED_BY");
				this.OnCREATED_BYChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATED_DATE", DbType="DateTime")]
	public System.Nullable<System.DateTime> CREATED_DATE
	{
		get
		{
			return this._CREATED_DATE;
		}
		set
		{
			if ((this._CREATED_DATE != value))
			{
				this.OnCREATED_DATEChanging(value);
				this.SendPropertyChanging();
				this._CREATED_DATE = value;
				this.SendPropertyChanged("CREATED_DATE");
				this.OnCREATED_DATEChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODIFIED_BY", DbType="VarChar(50)")]
	public string MODIFIED_BY
	{
		get
		{
			return this._MODIFIED_BY;
		}
		set
		{
			if ((this._MODIFIED_BY != value))
			{
				this.OnMODIFIED_BYChanging(value);
				this.SendPropertyChanging();
				this._MODIFIED_BY = value;
				this.SendPropertyChanged("MODIFIED_BY");
				this.OnMODIFIED_BYChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODIFIED_DATE", DbType="DateTime")]
	public System.Nullable<System.DateTime> MODIFIED_DATE
	{
		get
		{
			return this._MODIFIED_DATE;
		}
		set
		{
			if ((this._MODIFIED_DATE != value))
			{
				this.OnMODIFIED_DATEChanging(value);
				this.SendPropertyChanging();
				this._MODIFIED_DATE = value;
				this.SendPropertyChanged("MODIFIED_DATE");
				this.OnMODIFIED_DATEChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PCMH_Target", DbType="Int")]
	public System.Nullable<int> PCMH_Target
	{
		get
		{
			return this._PCMH_Target;
		}
		set
		{
			if ((this._PCMH_Target != value))
			{
				this.OnPCMH_TargetChanging(value);
				this.SendPropertyChanging();
				this._PCMH_Target = value;
				this.SendPropertyChanged("PCMH_Target");
				this.OnPCMH_TargetChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeadLine_Date", DbType="DateTime")]
	public System.Nullable<System.DateTime> DeadLine_Date
	{
		get
		{
			return this._DeadLine_Date;
		}
		set
		{
			if ((this._DeadLine_Date != value))
			{
				this.OnDeadLine_DateChanging(value);
				this.SendPropertyChanging();
				this._DeadLine_Date = value;
				this.SendPropertyChanged("DeadLine_Date");
				this.OnDeadLine_DateChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

public partial class PROC_GET_DASHBOARD_DEFAULT_SETTINGSResult
{
	
	private System.Nullable<long> _DASHBOARD_SETTINGS_ID;
	
	private string _DASHBOARD_ITEM;
	
	private System.Nullable<bool> _SHOW_ITEM;
	
	private System.Nullable<int> _POSITION;
	
	public PROC_GET_DASHBOARD_DEFAULT_SETTINGSResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DASHBOARD_SETTINGS_ID", DbType="BigInt")]
	public System.Nullable<long> DASHBOARD_SETTINGS_ID
	{
		get
		{
			return this._DASHBOARD_SETTINGS_ID;
		}
		set
		{
			if ((this._DASHBOARD_SETTINGS_ID != value))
			{
				this._DASHBOARD_SETTINGS_ID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DASHBOARD_ITEM", DbType="VarChar(100)")]
	public string DASHBOARD_ITEM
	{
		get
		{
			return this._DASHBOARD_ITEM;
		}
		set
		{
			if ((this._DASHBOARD_ITEM != value))
			{
				this._DASHBOARD_ITEM = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SHOW_ITEM", DbType="Bit")]
	public System.Nullable<bool> SHOW_ITEM
	{
		get
		{
			return this._SHOW_ITEM;
		}
		set
		{
			if ((this._SHOW_ITEM != value))
			{
				this._SHOW_ITEM = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POSITION", DbType="Int")]
	public System.Nullable<int> POSITION
	{
		get
		{
			return this._POSITION;
		}
		set
		{
			if ((this._POSITION != value))
			{
				this._POSITION = value;
			}
		}
	}
}

public partial class PCMH_PROC_GET_SURVEY_QUESTIONSResult
{
	
	private string _QUESTION;
	
	private long _ID;
	
	public PCMH_PROC_GET_SURVEY_QUESTIONSResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QUESTION", DbType="VarChar(300)")]
	public string QUESTION
	{
		get
		{
			return this._QUESTION;
		}
		set
		{
			if ((this._QUESTION != value))
			{
				this._QUESTION = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="BigInt NOT NULL")]
	public long ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this._ID = value;
			}
		}
	}
}

public partial class PCMH_PROC_SEARCH_PATIENTResult
{
	
	private long _Patient_Account;
	
	private string _Last_Name;
	
	private string _First_Name;
	
	private System.Nullable<char> _MI;
	
	private string _SSN;
	
	private System.Nullable<System.DateTime> _Date_Of_Birth;
	
	private string _Gender;
	
	private string _Marital_Status;
	
	private string _Address;
	
	private string _City;
	
	private string _State;
	
	private string _ZIP;
	
	private string _Home_Phone;
	
	private string _Business_Phone;
	
	private string _Email_Address;
	
	private string _Created_By;
	
	private System.Nullable<System.DateTime> _Created_Date;
	
	private string _Modified_By;
	
	private System.Nullable<System.DateTime> _Modified_Date;
	
	private System.Nullable<bool> _Deleted;
	
	private System.Nullable<long> _practice_code;
	
	public PCMH_PROC_SEARCH_PATIENTResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Patient_Account", DbType="BigInt NOT NULL")]
	public long Patient_Account
	{
		get
		{
			return this._Patient_Account;
		}
		set
		{
			if ((this._Patient_Account != value))
			{
				this._Patient_Account = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Last_Name", DbType="VarChar(50)")]
	public string Last_Name
	{
		get
		{
			return this._Last_Name;
		}
		set
		{
			if ((this._Last_Name != value))
			{
				this._Last_Name = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_First_Name", DbType="VarChar(50)")]
	public string First_Name
	{
		get
		{
			return this._First_Name;
		}
		set
		{
			if ((this._First_Name != value))
			{
				this._First_Name = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MI", DbType="Char(1)")]
	public System.Nullable<char> MI
	{
		get
		{
			return this._MI;
		}
		set
		{
			if ((this._MI != value))
			{
				this._MI = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SSN", DbType="Char(9)")]
	public string SSN
	{
		get
		{
			return this._SSN;
		}
		set
		{
			if ((this._SSN != value))
			{
				this._SSN = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date_Of_Birth", DbType="DateTime")]
	public System.Nullable<System.DateTime> Date_Of_Birth
	{
		get
		{
			return this._Date_Of_Birth;
		}
		set
		{
			if ((this._Date_Of_Birth != value))
			{
				this._Date_Of_Birth = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="VarChar(15)")]
	public string Gender
	{
		get
		{
			return this._Gender;
		}
		set
		{
			if ((this._Gender != value))
			{
				this._Gender = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Marital_Status", DbType="VarChar(10)")]
	public string Marital_Status
	{
		get
		{
			return this._Marital_Status;
		}
		set
		{
			if ((this._Marital_Status != value))
			{
				this._Marital_Status = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="VarChar(500)")]
	public string Address
	{
		get
		{
			return this._Address;
		}
		set
		{
			if ((this._Address != value))
			{
				this._Address = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="VarChar(50)")]
	public string City
	{
		get
		{
			return this._City;
		}
		set
		{
			if ((this._City != value))
			{
				this._City = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="Char(2)")]
	public string State
	{
		get
		{
			return this._State;
		}
		set
		{
			if ((this._State != value))
			{
				this._State = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZIP", DbType="VarChar(9)")]
	public string ZIP
	{
		get
		{
			return this._ZIP;
		}
		set
		{
			if ((this._ZIP != value))
			{
				this._ZIP = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Home_Phone", DbType="VarChar(10)")]
	public string Home_Phone
	{
		get
		{
			return this._Home_Phone;
		}
		set
		{
			if ((this._Home_Phone != value))
			{
				this._Home_Phone = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Business_Phone", DbType="VarChar(10)")]
	public string Business_Phone
	{
		get
		{
			return this._Business_Phone;
		}
		set
		{
			if ((this._Business_Phone != value))
			{
				this._Business_Phone = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email_Address", DbType="VarChar(50)")]
	public string Email_Address
	{
		get
		{
			return this._Email_Address;
		}
		set
		{
			if ((this._Email_Address != value))
			{
				this._Email_Address = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Created_By", DbType="VarChar(25)")]
	public string Created_By
	{
		get
		{
			return this._Created_By;
		}
		set
		{
			if ((this._Created_By != value))
			{
				this._Created_By = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Created_Date", DbType="DateTime")]
	public System.Nullable<System.DateTime> Created_Date
	{
		get
		{
			return this._Created_Date;
		}
		set
		{
			if ((this._Created_Date != value))
			{
				this._Created_Date = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Modified_By", DbType="VarChar(25)")]
	public string Modified_By
	{
		get
		{
			return this._Modified_By;
		}
		set
		{
			if ((this._Modified_By != value))
			{
				this._Modified_By = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Modified_Date", DbType="DateTime")]
	public System.Nullable<System.DateTime> Modified_Date
	{
		get
		{
			return this._Modified_Date;
		}
		set
		{
			if ((this._Modified_Date != value))
			{
				this._Modified_Date = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Deleted", DbType="Bit")]
	public System.Nullable<bool> Deleted
	{
		get
		{
			return this._Deleted;
		}
		set
		{
			if ((this._Deleted != value))
			{
				this._Deleted = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_practice_code", DbType="BigInt")]
	public System.Nullable<long> practice_code
	{
		get
		{
			return this._practice_code;
		}
		set
		{
			if ((this._practice_code != value))
			{
				this._practice_code = value;
			}
		}
	}
}
#pragma warning restore 1591
