#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="YN")]
public partial class TestDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  #endregion
	
	public TestDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["YNConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public TestDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public TestDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public TestDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public TestDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<WebsiteUser> WebsiteUsers
	{
		get
		{
			return this.GetTable<WebsiteUser>();
		}
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spAdduser")]
	public int spAdduser([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(150)")] string firstName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(150)")] string lastName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string gender, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Address", DbType="NVarChar(150)")] string address, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(150)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(150)")] string username, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(150)")] string password, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Result", DbType="Char(1)")] ref System.Nullable<char> result)
	{
		IExecuteResult result1 = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), firstName, lastName, gender, address, email, username, password, result);
		result = ((System.Nullable<char>)(result1.GetParameterValue(7)));
		return ((int)(result1.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spDeleteUser")]
	public int spDeleteUser([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(150)")] string username, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Result", DbType="Char(1)")] ref System.Nullable<char> result)
	{
		IExecuteResult result1 = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), username, result);
		result = ((System.Nullable<char>)(result1.GetParameterValue(1)));
		return ((int)(result1.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spUpdateUser")]
	public int spUpdateUser([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(150)")] string firstName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(150)")] string lastName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string gender, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Address", DbType="NVarChar(150)")] string address, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(150)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(150)")] string username, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Result", DbType="Char(1)")] ref System.Nullable<char> result)
	{
		IExecuteResult result1 = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), firstName, lastName, gender, address, email, username, result);
		result = ((System.Nullable<char>)(result1.GetParameterValue(6)));
		return ((int)(result1.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spValidateUser")]
	public int spValidateUser([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(150)")] string username, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(150)")] string password, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Result", DbType="Char(1)")] ref System.Nullable<char> result)
	{
		IExecuteResult result1 = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), username, password, result);
		result = ((System.Nullable<char>)(result1.GetParameterValue(2)));
		return ((int)(result1.ReturnValue));
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.WebsiteUser")]
public partial class WebsiteUser
{
	
	private int _Id;
	
	private string _FirstName;
	
	private string _LastName;
	
	private string _Gender;
	
	private string _Address;
	
	private string _Email;
	
	private string _UserName;
	
	private string _Password;
	
	public WebsiteUser()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this._Id = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
	public string FirstName
	{
		get
		{
			return this._FirstName;
		}
		set
		{
			if ((this._FirstName != value))
			{
				this._FirstName = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
	public string LastName
	{
		get
		{
			return this._LastName;
		}
		set
		{
			if ((this._LastName != value))
			{
				this._LastName = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string Gender
	{
		get
		{
			return this._Gender;
		}
		set
		{
			if ((this._Gender != value))
			{
				this._Gender = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
	public string Address
	{
		get
		{
			return this._Address;
		}
		set
		{
			if ((this._Address != value))
			{
				this._Address = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
	public string Email
	{
		get
		{
			return this._Email;
		}
		set
		{
			if ((this._Email != value))
			{
				this._Email = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
	public string UserName
	{
		get
		{
			return this._UserName;
		}
		set
		{
			if ((this._UserName != value))
			{
				this._UserName = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
	public string Password
	{
		get
		{
			return this._Password;
		}
		set
		{
			if ((this._Password != value))
			{
				this._Password = value;
			}
		}
	}
}
#pragma warning restore 1591
